language: ruby
cache: bundler

rvm:
  - 2.0.0
  - 1.9.3

script: 'bundle exec rake spec'

bundler_args: --without development

branches:
  only:
    - master

notifications:
  email:
    - mark.mcdx@gmail.com

